apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: liveservice
  name: liveservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: liveservice
status:
  loadBalancer: {}
