apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.liveServiceSpringProfilesActive }}
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.keycloakAuthServerUrl }}
  KEYCLOAK_REALM: {{ .Values.keycloakRealm }}
  KEYCLOAK_RESOURCE:  {{ .Values.agencyServiceKeycloakResource }}
  APP_BASE_URL: "*"
  SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
  {{- if .Values.zipkin.enabled }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "{{ .Values.zipkin.tracing.endpoint }}"
  {{- end }}
  MANAGEMENT_TRACING_ENABLED: {{ .Values.zipkin.enabled | default false | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}/protocol/openid-connect/certs"
  SPRING_JWT_AUTH_CONVERTER_RESOURCEID: "{{ .Values.keycloakserviceAppClientid }}"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: liveservice-{{ .Release.Name }}-env
  name: liveservice-{{ .Release.Name }}-env