{{- if .Values.global.adminConsoleEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: adminconsole
  name: adminconsole
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: adminconsole
status:
  loadBalancer: {}
{{- end }}