{{- if .Values.global.adminConsoleEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.network/adminconsole_network: "true"
    io.kompose.service: adminconsole
  name: adminconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminconsole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/adminconsole_network: "true"
        io.kompose.network/service_network: "true"
        io.kompose.service: adminconsole
    spec:
      containers:
        - image:  {{ .Values.adminconsoleImageName }}:{{ .Values.adminconsoleImageVersion }}
          imagePullPolicy: Always
          name: adminconsole
          ports:
            - containerPort: 80
          {{- if .Values.adminconsole }}
          {{- if .Values.adminconsole.resources }}
          resources:
            {{- if .Values.adminconsole.resources.requests }}
            requests:
              {{- if .Values.adminconsole.resources.requests.memory }}
              memory: {{  .Values.adminconsole.resources.requests.memory }}
              {{- end}}
              {{- if .Values.adminconsole.resources.requests.cpu }}
              cpu: {{ .Values.adminconsole.resources.requests.cpu }}
              {{- end}}
            {{- end }}
            {{- if .Values.adminconsole.resources.limits }}
            limits:
              {{- if .Values.adminconsole.resources.limits.memory }}
              memory: {{ .Values.adminconsole.resources.limits.memory }}
              {{- end}}
              {{- if .Values.adminconsole.resources.limits.cpu }}
              cpu: {{ .Values.adminconsole.resources.limits.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
status: {}
{{- end }}