{{- if .Values.global.adminConsoleEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.network/adminconsole_network: "true"
    io.kompose.service: adminconsole
  name: adminconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminconsole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/adminconsole_network: "true"
        io.kompose.network/service_network: "true"
        io.kompose.service: adminconsole
    spec:
      containers:
        - image:  {{ .Values.adminconsoleImageName }}:{{ .Values.adminconsoleImageVersion }}
          imagePullPolicy: Always
          name: adminconsole
          ports:
            - containerPort: 80
          {{- if .Values.resources.adminconsole }}
          resources:
            {{- if .Values.resources.adminconsole.requests }}
            requests:
              {{- if .Values.resources.adminconsole.requests.memory }}
              memory: {{  .Values.resources.adminconsole.requests.memory }}
              {{- end}}
              {{- if .Values.resources.adminconsole.requests.cpu }}
              cpu: {{ .Values.resources.adminconsole.requests.cpu }}
              {{- end}}
            {{- end }}
            {{- if .Values.resources.adminconsole.limits }}
            limits:
              {{- if .Values.resources.adminconsole.limits.memory }}
              memory: {{ .Values.resources.adminconsole.limits.memory }}
              {{- end}}
              {{- if .Values.resources.adminconsole.limits.cpu }}
              cpu: {{ .Values.resources.adminconsole.limits.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
status: {}
{{- end }}