apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: s247agent
  name: s247agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
