{{- if .Values.global.migrationToolEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrationtool
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.migrationToolImageName }}:{{ .Values.migrationToolImageVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: migrationtool-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERSERVICE_URL
                  name: migrationtool-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERSERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERSERVICE_PASSWORD
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: SPRING_DATASOURCE_USERSERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERSERVICE_USERNAME
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_AUTH_SERVER_URL
                  name: migrationtool-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CONFIG_ADMIN_USERNAME
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: KEYCLOAK_CONFIG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_CONFIG_ADMIN_PASSWORD
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: ROCKETCHAT_CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: ROCKETCHAT_CONFIG_SERVER_URL
                  name: migrationtool-{{ .Release.Name }}-env
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: MIGRATION_SPRING_PROFILE
                  name: migrationtool-{{ .Release.Name }}-env
            - name: ROCKETCHAT_CONFIG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROCKETCHAT_CONFIG_ADMIN_PASSWORD
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: ROCKETCHAT_CONFIG_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: ROCKETCHAT_CONFIG_ADMIN_USERNAME
                  name: migrationtool-secret-{{ .Release.Name }}-env
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: migrationtool-secret-{{ .Release.Name }}-env
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-secret
{{- end }}