{{- if .Values.weblateCustomResourcesPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrationservice-resource-{{ .Release.Name }}-configmap
data:
  {{- $path := printf "%s/*.json" "resources/" }}
    {{- (.Files.Glob $path).AsConfig | nindent 2 }}
{{- end }}
