{{- if .Values.global.migrationToolEnabled }}
apiVersion: v1
kind: ConfigMap
data:
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/migrationservice"
  ROCKETCHAT_CONFIG_SERVER_URL: "http://rocketchat.{{ .Release.Namespace }}:3000/api"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak.{{ .Release.Namespace }}:8080/auth"
  SPRING_DATASOURCE_USERSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/userservice"
  SPRING_DATASOURCE_AGENCYSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/agencyservice"
  SPRING_DATASOURCE_TENANTSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/tenantservice"
  SPRING_DATASOURCE_CONSULTINGTYPESERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/consultingtypeservice"
  MIGRATION_SPRING_PROFILE: "{{ .Values.migrationToolSpringProfile }}"

  USERS_JITSI_TECHNICAL_PASSWORD: "{{ .Values.jitsiTechnicalPassword }}"
  USERS_JITSI_TECHNICAL_EMAIL: "{{ .Values.jitsiTechnicalEmail }}"
  USERS_JITSI_TECHNICAL_TENANTID: "{{ .Values.jitsiTechnicalTenantId }}"

  USERS_PUBLIC_PLAN_TECHNICAL_PASSWORD: "{{ .Values.publicPlanTechnicalPassword }}"
  USERS_PUBLIC_PLAN_TECHNICAL_EMAIL: "{{ .Values.publicPlanTechnicalEmail }}"
  USERS_PUBLIC_PLAN_TECHNICAL_TENANTID: "{{ .Values.publicPlanTechnicalTenantId }}"

  WEBLATE_CONFIG_SERVER_URL: "{{ .Values.weblateServerUrl }}"
  WEBLATE_CONFIG_API_KEY: "{{ .Values.weblateApiKey }}"
  WEBLATE_CONFIG_PROJECT_NAME: {{ .Values.weblateProjectName | default "onlineberatung" }}
  WEBLATE_CONFIG_PROJECT_SLUG: {{ .Values.weblateProjectSlug | default "onlineberatung" }}
  WEBLATE_CONFIG_WEB: "{{ .Values.weblateProjectWebUrl }}"
  WEBLATE_CONFIG_USE_CUSTOM_RESOURCES_PATH: "{{ .Values.weblateUseCustomResourcesPath | default false }}"
  WEBLATE_CONFIG_CUSTOM_RESOURCES_PATH: {{ .Values.weblateCustomResourcesPath | default "resources/weblate" }}

metadata:
  labels:
    io.kompose.service: migrationtool-{{ .Release.Name }}-env
  name: migrationtool-{{ .Release.Name }}-env
{{- end }}