{{- if .Values.global.migrationToolEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: migrationtool-secret-{{ .Release.Name }}-env
type: Opaque
data:
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/consulting_types?retryWrites=false" .Values.global.consultingTypeMongoUser .Values.global.consultingTypeMongoPass .Release.Namespace }}
  SPRING_DATA_MONGODB_URI: {{ $mongourl | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.keycloakserviceAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.keycloakserviceAdminPassword | b64enc | quote }}
  ROCKETCHAT_CONFIG_ADMIN_USERNAME: {{ .Values.rocketAdminUsername | b64enc | quote }}
  ROCKETCHAT_CONFIG_ADMIN_PASSWORD: {{ .Values.rocketAdminPassword | b64enc | quote }}
{{- end }}