{{- if .Values.global.migrationToolEnabled }}
apiVersion: v1
kind: ConfigMap
data:
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/migrationservice"
  {{- else }}
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/migrationservice"
  {{- end }}
  ROCKETCHAT_CONFIG_SERVER_URL: "http://rocketchat.{{ .Release.Namespace }}:3000/api"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak.{{ .Release.Namespace }}:8080/auth"
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_USERSERVICE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/userservice"
  {{- else }}
  SPRING_DATASOURCE_USERSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/userservice"
  {{- end }}
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_AGENCYSERVICE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/agencyservice"
  {{- else }}
  SPRING_DATASOURCE_AGENCYSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/agencyservice"
  {{- end }}
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_TENANTSERVICE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/tenantservice"
  {{- else }}
  SPRING_DATASOURCE_TENANTSERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/tenantservice"
  {{- end }}
  {{- if .Values.global.useExternalMariaDb }}
  SPRING_DATASOURCE_CONSULTINGTYPESERVICE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/consultingtypeservice"
  {{- else }}
  SPRING_DATASOURCE_CONSULTINGTYPESERVICE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/consultingtypeservice"
  {{- end }}
  MIGRATION_SPRING_PROFILE: "{{ .Values.migrationToolSpringProfile }}"

  USERS_JITSI_TECHNICAL_PASSWORD: "{{ .Values.jitsiTechnicalPassword }}"
  USERS_JITSI_TECHNICAL_EMAIL: "{{ .Values.jitsiTechnicalEmail }}"
  USERS_JITSI_TECHNICAL_TENANTID: "{{ .Values.jitsiTechnicalTenantId }}"

  USERS_PUBLIC_PLAN_TECHNICAL_PASSWORD: "{{ .Values.publicPlanTechnicalPassword }}"
  USERS_PUBLIC_PLAN_TECHNICAL_EMAIL: "{{ .Values.publicPlanTechnicalEmail }}"
  USERS_PUBLIC_PLAN_TECHNICAL_TENANTID: "{{ .Values.publicPlanTechnicalTenantId }}"

  WEBLATE_CONFIG_API_URL: "{{ .Values.weblate.api.url | default (printf "%s.%s" "weblate" .Release.Namespace)}}"
  WEBLATE_CONFIG_WEB: "https://{{ .Values.global.domainName }}"
  WEBLATE_CONFIG_USE_CUSTOM_RESOURCES_PATH: "{{ .Values.migration.weblate.useCustomResourcesPath | default false }}"
  WEBLATE_CONFIG_CUSTOM_RESOURCES_PATH: "{{ .Values.migration.weblate.customResourcesPath | default "resources/weblate/" }}"

metadata:
  labels:
    io.kompose.service: migrationtool-{{ .Release.Name }}-env
  name: migrationtool-{{ .Release.Name }}-env
{{- end }}
