apiVersion: v1
kind: Secret
metadata:
  name: videoservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  VIDEO_CALL_SECURITY_JWT_SECRET: {{ .Values.videoCallSecurityJwtSecret | b64enc | quote }}