apiVersion: v1
kind: Secret
metadata:
  name: videoservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  VIDEO_CALL_SECURITY_JWT_SECRET: {{ .Values.videoCallSecurityJwtSecret | b64enc | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  VIDEOSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.videoServiceSpringDatasourceUsername | b64enc | quote }}
  VIDEOSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.videoServiceSpringDatasourcePassword | b64enc | quote }}