apiVersion: v1
data:
    # General
  {{- if .Values.global.enableTls }}
    APP_BASE_URL: "https://{{ .Values.global.domainName }}"
  {{- else }}
    APP_BASE_URL: "http://{{ .Values.global.domainName }}"
  {{- end }}
    # Spring
  {{- if .Values.global.useExternalMariaDb }}
    SPRING_DATASOURCE_URL: "jdbc:mariadb://{{ .Values.global.mariaDbHost }}:3306/videoservice"
  {{- else }}
    SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb.{{ .Release.Namespace }}:3306/videoservice"
  {{- end }}
    SPRING_PROFILES_ACTIVE: {{ .Values.videoServiceSpringProfilesActive }}
    # Keycloak
    KEYCLOAK_AUTH_SERVER_URL: {{ .Values.keycloakAuthServerUrl }}
    KEYCLOAK_REALM: {{ .Values.keycloakRealm }}
    KEYCLOAK_PRINCIPAL_ATTRIBUTE: {{ .Values.keycloakPrincipalAttribute }}
    KEYCLOAK_RESOURCE: {{ .Values.videoServiceKeycloakResource }}
    KEYCLOAK_CORS: "false"
    # Services
    USER_SERVICE_API_URL: "http://userservice.{{ .Release.Namespace }}:8080"
    LIVE_SERVICE_API_URL: "http://liveservice.{{ .Release.Namespace }}:8080"
    VIDEO_CALL_SERVER_URL: {{ .Values.videoCallServerUrl }}
    # CSRF
    CSRF_HEADER_PROPERTY: {{ .Values.csrfHeaderProperty }}
    CSRF_COOKIE_PROPERTY: {{ .Values.csrfCookieProperty }}
    # Logging
    #LOGGING_LEVEL_ROOT: "DEBUG;
    VIDEO_CALL_SECURITY_JWT_AUDIENCE: {{ .Values.videoCallSecurityJwtAudience }}
    VIDEO_CALL_SECURITY_JWT_ISSUER: {{ .Values.videoCallSecurityJwtIssuer }}
    VIDEO_CALL_SECURITY_JWT_SUBJECT: {{ .Values.videoCallSecurityJwtSubject }}
    VIDEO_CALL_SECURITY_JWT_VALIDITY_HOURS: "3"
    MESSAGE_SERVICE_API_URL: "http://messageservice.{{ .Release.Namespace }}:8080"
    MULTITENANCY_ENABLED: {{ .Values.global.multitenancyEnabled | quote }}
    TENANT_SERVICE_API_URL: "http://tenantservice.{{ .Release.Namespace }}:8080"
    FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED: {{ .Values.global.multitenancyWithSingleDomainEnabled | quote }}
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: videoservice-{{ .Release.Name }}-env
  name: videoservice-{{ .Release.Name }}-env
