{{- if .Values.global.initializeDummyData }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-rocketchat-user
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: create-mongo-rocketchat
          image: {{ .Values.mongoImageName }}:{{ .Values.mongoVersion }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_ROCKETCHAT_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROCKETCHAT_USER
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_ROCKETCHAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROCKETCHAT_PASSWORD
                  name: mongodb-secret-{{ .Release.Name }}-env
          command:
            - /bin/bash
            - -c
            - >
              mongosh "mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb.{{ .Release.Namespace }}:27017"
              --eval
              "db = db.getSiblingDB('rocketchat');
              db.createUser({
                user: '$MONGODB_ROCKETCHAT_USER',
                pwd: '$MONGODB_ROCKETCHAT_PASSWORD',
                roles: [{ role: 'readWrite', db: 'rocketchat' }]});
              db.runCommand({
                grantRolesToUser: '$MONGODB_ROCKETCHAT_USER',
                roles: [{ role: 'clusterMonitor', db: 'admin' }]});"
      restartPolicy: Never
  backoffLimit: 1
 {{- end }}