apiVersion: v1
kind: Secret
metadata:
  labels:
    io.kompose.service: mongodb-replica-{{ .Release.Name }}-secret
  name: mongodb-replica-{{ .Release.Name }}-secret
type: Opaque
data:
  replica.key.tmp: {{ .Values.mongoSharedKey | b64enc | quote }}
