apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.global.mongoInitDbRootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.global.mongoInitDbRootPassword | b64enc | quote }}
  MONGO_NOSQLCLIENT_USER: {{ .Values.global.nosqlclientMongoUsername | b64enc | quote }}
  MONGO_NOSQLCLIENT_PASSWORD: {{ .Values.global.nosqlclientMongoPassword | b64enc | quote }}
  MONGO_ROCKETCHAT_USER: {{ .Values.global.rocketchatMongoUsername | b64enc | quote }}
  MONGO_ROCKETCHAT_PASSWORD: {{ .Values.global.rocketchatMongoPassword | b64enc | quote }}
  MONGO_OPLOG_USER: {{ .Values.global.oplogMongoUsername | b64enc | quote }}
  MONGO_OPLOG_PASSWORD: {{ .Values.global.oplogMongoPassword | b64enc | quote }}
  MONGO_STATISTICS_USER: {{ .Values.global.statisticsMongoUser | b64enc | quote }}
  MONGO_STATISTICS_PASSWORD: {{ .Values.global.statisticsMongoPass | b64enc | quote }}
  MONGO_CONSULTING_TYPES_USER: {{ .Values.global.consultingTypeMongoUser | b64enc | quote }}
  MONGO_CONSULTING_TYPES_PASSWORD: {{ .Values.global.consultingTypeMongoPass | b64enc | quote }}