name: online-counseling
description: Helm chart for the online counseling plattform
version: 0.0.1
apiVersion: v1
keywords:
  - online-counseling
sources:
  - https://github.com/Onlineberatung/onlineBeratung-kubernetes.git
type: application
dependencies:
  - name: weblate
    version: "5.1.1.3"
    repository: "file://helm/charts/weblate"
