apiVersion: v1
kind: Secret
metadata:
  name: mailservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_MAIL_USERNAME: {{ .Values.springMailUsername | b64enc | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.springMailPassword | b64enc | quote }}
  MAIL_EXCHANGE_USER: {{ .Values.mailExchangeUser | b64enc | quote }}
  MAIL_EXCHANGE_PASSWORD: {{ .Values.mailExchangePassword | b64enc | quote }}
  WEBLATE_API_URL: {{ .Values.weblate.apiUrl | b64enc | quote }}
  WEBLATE_API_KEY: {{ .Values.weblate.apiKey | b64enc | quote }}

