apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.mailServiceSpringProfilesActive }}

  SPRING_MAIL_HOST: {{ .Values.springMailHost | quote }}
  SPRING_MAIL_PORT: {{ .Values.springMailPort | default "587" | quote }}
  SPRING_MAIL_PROTOCOL: {{ .Values.springMailProtocol | default "smtp" | quote }}
  SPRING_MAIL_DEFAULT_ENCODING: {{ .Values.springMailDefaultEncoding | default "UTF-8" | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: {{ .Values.springMailPropertiesMailTransportProtocol | default "smtp" | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_PORT: {{ .Values.springMailPropertiesMailSmtpPort | default "587" | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: {{ .Values.springMailPropertiesMailSmtpAuth | default "true" | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: {{ .Values.springMailPropertiesMailSmtpStarttlsEnable | default "true" | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: {{ .Values.springMailPropertiesMailSmtpStarttlsRequired | default "true" | quote }}

  MAIL_SENDER: {{ .Values.mailSender }}
  MAIL_ERROR_RECIPIENTS: {{ .Values.mailErrorRecipients }}
  MAIL_FIX_RECIPIENT: {{ .Values.fixRecipient | default "" | quote }}
  APP_IMPRINT_URL: {{ .Values.appImprintUrl }}
  APP_DATAPRIVACY_URL: {{ .Values.appDataprivacyUrl }}
  MAIL_USESMTP: "true"
  MAIL_EXCHANGE_URL: ""
  MAIL_EXCHANGE_VERSION: ""
  CSRF_HEADER_PROPERTY:  {{ .Values.csrfHeaderProperty }}
  CSRF_COOKIE_PROPERTY: {{ .Values.csrfCookieProperty }}
  LOGGING_LEVEL_ROOT: {{ .Values.mailServiceLoggingLevelRoot }}
  TEMPLATE_USE_CUSTOM_RESOURCES_PATH: {{ .Values.mailService.useCustomResourcePath | default "true" | quote }}
  TEMPLATE_CUSTOM_RESOURCES_PATH: "mailserviceTemplates/"
  TEMPLATE_CUSTOM_DEFAULT_TRANSLATIONS_PATH: {{ .Values.customDefaultTranslationsPath | default "mailservice/i18n/" | quote }}
  WEBLATE_API_URL: {{ .Values.weblate.api.url }}
  WEBLATE_PROJECT: {{ .Values.weblate.project.name }}
  WEBLATE_COMPONENT: {{ .Values.weblate.component.mail.name }}
  {{- if .Values.mailServiceCacheConfigurationTargetDirectory }}
  SPRING_CACHE_JCACHE_CONFIG: {{ printf "%s%s%s" "file:" .Values.mailServiceCacheConfigurationTargetDirectory "/ehcache.xml" | quote }}
  {{- end }}

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: mailservice-{{ .Release.Name }}-env
  name: mailservice-{{ .Release.Name }}-env