apiVersion: v1
kind: Secret
metadata:
  name: agencyservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  AGENCYSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.agencyServiceSpringDatasourceUsername | b64enc | quote }}
  AGENCYSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.agencyServiceSpringDatasourcePassword | b64enc | quote }}
