apiVersion: v2
# renovate: datasource=docker depName=weblate/weblate
appVersion: 5.1.1.3
description: Weblate is a free web-based translation management system.
name: online-counseling-weblate
type: application
version: 0.5.2
home: https://weblate.org/
icon: https://s.weblate.org/cdn/weblate.svg
keywords:
  - online-counseling-weblate
dependencies:
- name: postgresql
  version: 13.2.0
  repository: https://charts.bitnami.com/bitnami
# condition: postgresql.enabled
- name: redis
  version: 18.2.0
  repository: https://charts.bitnami.com/bitnami
#  condition: redis.enabled
