apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secret-{{ .Release.Name }}-env
  namespace: jitsi
  labels:
    app: app
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: {{ .Values.jicofoComponentSecret | b64enc | quote }}
  JICOFO_AUTH_USER: {{ .Values.jicofoAuthUser | b64enc | quote }}
  JICOFO_AUTH_PASSWORD: {{ .Values.jicofoAuthPassword | b64enc | quote }}
  JVB_AUTH_PASSWORD: {{ .Values.jvbAuthPassword | b64enc | quote }}
  JVB_AUTH_USER: {{ .Values.jvbAuthUser | b64enc | quote }}
  JIBRI_RECORDER_PASSWORD: {{ .Values.jibriRecorderPassword | b64enc | quote }}
  JIBRI_RECORDER_USER: {{ .Values.jibriRecorderUser | b64enc | quote }}
  JIBRI_XMPP_PASSWORD: {{ .Values.jibriXmppPassword | b64enc | quote }}
  JIBRI_XMPP_USER: {{ .Values.jibriXmppUser | b64enc | quote }}
  JIGASI_XMPP_PASSWORD: {{ .Values.jigasiXmppPassword | b64enc | quote }}
  JIGASI_XMPP_USER: {{ .Values.jigasiXmppUser | b64enc | quote }}
  JWT_ACCEPTED_AUDIENCES: {{ .Values.jwtAcceptedAudiences | b64enc | quote }}
  JWT_ACCEPTED_ISSUERS: {{ .Values.jwtAcceptedIssuers | b64enc | quote }}
  JWT_APP_ID: {{ .Values.jwtAppId | b64enc | quote }}
  JWT_APP_SECRET: {{ .Values.jwtAppSecret | b64enc | quote }}
  TURN_CREDENTIALS: {{ .Values.turnCredentials | b64enc | quote }}
