{{- if .Values.global.translationManagementSystemEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: weblate-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: saas
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.0.0
    helm.sh/chart: postgresql-13.0.0
type: Opaque
data:
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}
{{- end }}
