apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  DB_USER: {{ .Values.global.keycloakDbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.global.keycloakDbPassword | b64enc | quote }}