apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-statistics-plugin-{{ .Release.Name }}-configmap
  namespace: jitsi
data:
  statistics.cfg.lua: |
    enable_statistics = {{ .Values.global.statisticsEnabled }}
    rabbit_url = "http://rabbitmq.{{ .Release.Namespace }}:15672/api/exchanges/%2F/statistics.topic/publish"
    rabbit_username = "{{ .Values.global.rabbitStatisticsUser }}"
    rabbit_password = "{{ .Values.global.rabbitStatisticsPassword }}"
