apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: jitsi-prosody
  namespace: jitsi
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.videoCallServerUrl }}
      http:
        paths:
          - backend:
              service:
                name: prosody
                port:
                  number: 5280
            path: /(http-bind|xmpp-websocket)
            pathType: Prefix
