{{- if .Values.global.counselingToolsEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budibase
  namespace: budibase
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 150M
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 96k
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.budibaseCorsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.budibaseCorsAllowHeaders }}"
spec:
  {{- if .Values.global.enableTls }}
  tls:
    - hosts:
        - {{ .Values.budibaseHost }}
      secretName: {{ .Values.budibaseHost }}
  {{- end }}
  rules:
    - host: "{{ .Values.budibaseHost }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vi-proxy-service
                port:
                  number: 8080
          - path: /api/self
            pathType: Prefix
            backend:
              service:
                name: vi-proxy-service
                port:
                  number: 8080
          - path: /api/bbtel/ping
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/routing/client
            pathType: Prefix
            backend:
              service:
                name: vi-proxy-service
                port:
                  number: 8080
          - path: /api/system/environment
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/applications
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/global/self
            pathType: Prefix
            backend:
              service:
                name: vi-proxy-service
                port:
                  number: 8080
          - path: /api/global/auth
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/global/configs
            pathType: Prefix
            backend:
              service:
                name: vi-proxy-service
                port:
                  number: 8080
          - path: /api/global/configs/public
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/global/configs/checklist
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/tables
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
          - path: /api/queries
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
  {{- end }}