{{- if .Values.global.counselingToolsEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budibase
  namespace: budibase
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 150M
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 96k
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.budibaseCorsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.budibaseCorsAllowHeaders }}"
spec:
  {{- if .Values.global.enableTls }}
  tls:
    - hosts:
        - {{ .Values.budibaseHost }}
      secretName: {{ .Values.budibaseHost }}
  {{- end }}
  rules:
    - host: "{{ .Values.budibaseHost }}"
      http:
        paths:
          - backend:
              service:
                name: proxy-service
                port:
                  number: 10000
            path: /
            pathType: Prefix
{{- end }}