{{- if .Values.global.counselingToolsEnabled (ne .Release.Namespace "develop") }}
apiVersion: v1
kind: Service
metadata:
  name: vi-proxy-service
  namespace: budibase
spec:
  type: ExternalName
  externalName: counselingtoolsservice.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}