{{- if .Values.global.counselingToolsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: counselingtoolsservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.global.keycloakserviceAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.global.keycloakserviceAdminPassword | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_USERNAME: {{ .Values.global.keycloakserviceTechnicalUsername | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_PASSWORD: {{ .Values.global.keycloakserviceTechnicalPassword | b64enc | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  COUNSELINGTOOLSSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.counselingToolsServiceSpringDatasourceUsername | b64enc | quote }}
  COUNSELINGTOOLSSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.counselingToolsSpringDatasourcePassword | b64enc | quote }}
{{- end }}