keycloakImageName: "keycloak"
keycloakVersion: "dockerimage.v.2022-12-28.m1"

dbVendor: "MARIADB"
dbDatabase: "keycloak"

# Logging
# Supported log levels are ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE and WARN.
keycloakLogLevel: "WARN"
rootLogLevel: "WARN"

keycloakDbUser: "keycloak"
keycloakDbPassword: "keycloak"