apiVersion: v1
kind: Secret
metadata:
  name: uploadservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  UPLOADSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.uploadServiceSpringDatasourceUsername | b64enc | quote }}
  UPLOADSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.uploadServiceSpringDatasourcePassword | b64enc | quote }}
  ROCKET_TECHNICAL_USERNAME:  {{ .Values.rocketTechnicalUsername  | b64enc | quote }}
  ROCKET_TECHNICAL_PASSWORD:  {{ .Values.rocketTechnicalPassword  | b64enc | quote }}
  ROCKET_SYSTEMUSER_USERNAME: {{ .Values.rocketSystemuserUsername | b64enc | quote }}
  ROCKET_SYSTEMUSER_PASSWORD: {{ .Values.rocketSystemuserPassword | b64enc | quote }}
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/rocketchat?retryWrites=false" .Values.global.rocketchatMongoUsername .Values.global.rocketchatMongoPassword .Release.Namespace }}
  MONGODB_URI: {{ $mongourl | b64enc | quote }}
