apiVersion: v1
kind: ConfigMap
metadata:
  name: consultingtypeservice-settings-{{ .Release.Name }}-configmap
data:
  {{- $path := printf "%s/**.json" .Values.consultingTypesJsonPath }}
  {{- (.Files.Glob $path).AsConfig | nindent 2 }}
