apiVersion: v1
kind: Secret
metadata:
  name: consultingtypeservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/consulting_types?retryWrites=false" .Values.global.consultingTypeMongoUser .Values.global.consultingTypeMongoPass .Release.Namespace }}
  SPRING_DATA_MONGODB_URI: {{ $mongourl | b64enc | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.global.springLiquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.springLiquibasePassword | b64enc | quote }}
  CONSULTINGTYPESERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.consultingTypeServiceSpringDatasourceUsername | b64enc | quote }}
  CONSULTINGTYPESERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.consultingTypeServiceSpringDatasourcePassword | b64enc | quote }}

