{{- if not .Values.global.useExternalMariaDb }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mariadb
status:
  loadBalancer: {}
{{- end }}