{{- if not .Values.global.useExternalMariaDb }}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword | b64enc | quote }}
{{- end }}