apiVersion: v1
data:
    # Keycloak
    KEYCLOAK_AUTH_SERVER_URL: {{ .Values.keycloakAuthServerUrl }}
    KEYCLOAK_REALM: {{ .Values.keycloakRealm }}
    KEYCLOAK_PRINCIPAL_ATTRIBUTE: {{ .Values.keycloakPrincipalAttribute }}
    KEYCLOAK_RESOURCE: "statistics-service"
    KEYCLOAK_CORS: "false"
    # CSRF
    CSRF_HEADER_PROPERTY: {{ .Values.csrfHeaderProperty }}
    CSRF_COOKIE_PROPERTY: {{ .Values.csrfCookieProperty }}
    MULTITENANCY_ENABLED: {{ .Values.global.multitenancyEnabled | quote }}
    FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED: {{ .Values.global.multitenancyWithSingleDomainEnabled | quote }}
    TENANT_SERVICE_API_URL: "http://tenantservice.{{ .Release.Namespace }}:8080"
    CONSULTING_TYPE_SERVICE_API_URL: "http://consultingtypeservice.{{ .Release.Namespace }}:8080"
    {{- if .Values.zipkin.enabled }}
    SPRING_ZIPKIN_BASE_URL: "{{ .Values.zipkin.baseUrl }}"
    {{- end }}
    SPRING_SLEUTH_WEB_ENABLED: {{ .Values.zipkin.enabled | default false | quote }}
    SPRING_SLEUTH_SAMPLER_PERCENTAGE: {{ .Values.zipkin.samplerPercentage | default "1.0" | quote }}
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: "{{ .Values.keycloakAuthServerUrl }}/realms/{{ .Values.keycloakRealm }}/protocol/openid-connect/certs"
    SPRING_JWT_AUTH_CONVERTER_RESOURCEID: "{{ .Values.keycloakserviceAppClientid }}"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: statisticsservice-{{ .Release.Name }}-env
  name: statisticsservice-{{ .Release.Name }}-env
