apiVersion: v1
kind: Secret
metadata:
  name: statisticsservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  SPRING_RABBITMQ_USERNAME: {{ .Values.global.rabbitStatisticsUser | b64enc | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.global.rabbitStatisticsPassword | b64enc | quote }}
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/statistics?retryWrites=false" .Values.global.statisticsMongoUser .Values.global.statisticsMongoPass .Release.Namespace }}
  SPRING_DATA_MONGODB_URI: {{ $mongourl | b64enc | quote }}
