apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  LOCALIZATION_WEBLATE_API_KEY: {{ .Values.frontend.node.localization.weblate.api.key | b64enc | quote }}
  FRONTEND_WEBLATE_API_KEY: {{ .Values.frontend.react.weblate.api.key | b64enc | quote }}
