apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  ports:
    - name: "389"
      port: 389
      targetPort: 1389
  selector:
    io.kompose.service: openldap
status:
  loadBalancer: {}
