apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: openldap-data
  name: openldap-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
