apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.network/ldap_network: "true"
    io.kompose.service: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/ldap_network: "true"
        io.kompose.service: openldap
    spec:
      initContainers:
        - name: add-folder-permissions
          image: "bash"
          command: [ "/usr/local/bin/bash", "-c" ]
          args:
            - >
              chmod -R 777 /bitnami/openldap;
          volumeMounts:
            - mountPath: /bitnami/openldap
              name: openldap-data
      {{- if .Values.global.initializeDummyData }}
        - name: wait-for-ldap-dump
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ ! -f /init/data/ldap-database-initialized.lock ]; do
                sleep 15;
              done
          volumeMounts:
            - mountPath: /init/data
              name: plattform-init-data
      {{- end }}
      containers:
        - env:
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_USERNAME
                  name: openldap-secret-{{ .Release.Name }}-env
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_PASSWORD
                  name: openldap-secret-{{ .Release.Name }}-env
            - name: LDAP_ROOT
              value: {{ .Values.olcRootDn }}
            - name: LDAP_USER_DC
              value: {{ .Values.ouConfUsersDn }}
          image: {{ .Values.openldapImageName }}:{{ .Values.openldapVersion }}
          name: openldap
          ports:
            - containerPort: 1389
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/openldap
              name: openldap-data
            - mountPath: /ob-config
              name: openldap-config
      restartPolicy: Always
      volumes:
        - name: openldap-data
          persistentVolumeClaim:
            claimName: openldap-data
        - name: openldap-config
          configMap:
            name: openldap-{{ .Release.Name }}-config
        {{- if .Values.global.initializeDummyData }}
        - name: plattform-init-data
          persistentVolumeClaim:
            claimName: plattform-initialization-data
        {{- end }}
