apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  # Das Administrator Kennwort für die LDAP Verbindung
  LDAP_ADMIN_USERNAME: {{ .Values.adminUsername | b64enc | quote }}
  LDAP_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
