apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-mnesia
  name: rabbitmq-mnesia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
