apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config-{{ .Release.Name }}-configmap
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    vm_memory_high_watermark.absolute = 2GB
    disk_free_limit.absolute = 2GB
    default_user = {{ .Values.rabbitDefaultUser }}
    default_pass = {{ .Values.rabbitDefaultPass }}
    {{- if .Values.global.initializeDummyData }}
    load_definitions = /var/lib/rabbitmq/mnesia/rabbit_rabbitmq_dump.json
    {{- end }}