apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: web
  name: web
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: web
  template:
    metadata:
      labels:
        k8s-app: web
    spec:
      containers:
        - name: web
          ports:
          - containerPort: 80
          - containerPort: 443
          image: {{ .Values.webImageName }}:{{ .Values.webVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: prosody
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://prosody:5280
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_RECORDER_DOMAIN
              value: recorder.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: UTC
            - name: ENABLE_CLOSE_PAGE
              value: "1"
            - name: ENABLE_GUESTS
              value: "0"
            - name: ENABLE_PREJOIN_PAGE
              value: "0"
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: ENABLE_END_CONFERENCE
              value: "0"
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  key: VIDEOCALL_SERVER_URL
                  name: jitsi-prosody-{{ .Release.Name }}-env
          volumeMounts:
            - mountPath: /config/custom-config.js
              name: jitsi-web-config
              subPath: "custom-config.js"
            - mountPath: /config/custom-interface_config.js
              name: jitsi-web-config
              subPath: "custom-interface_config.js"
            - mountPath: /usr/share/jitsi-meet/images/custom
              name: jitsi-web-images
            - mountPath: /usr/share/jitsi-meet/body.html
              name: jitsi-web-html
              subPath: "body.html"
            - mountPath: /usr/share/jitsi-meet/static
              name: jitsi-web-static
            - mountPath: /usr/share/jitsi-meet/dynamicBranding.json
              name: jitsi-web-html
              subPath: "dynamicBranding.json"
            - mountPath: /usr/share/jitsi-meet/css/styles.css
              name: jitsi-web-css
              subPath: "styles.css"
            - mountPath: /usr/share/jitsi-meet/css/styles.css.map
              name: jitsi-web-css
              subPath: "styles.css.map"
      volumes:
            - name: jitsi-web-css
              configMap:
                name: jitsi-web-css-{{ .Release.Name }}-configmap
            - name: jitsi-web-images
              configMap:
                name: jitsi-web-images-{{ .Release.Name }}-configmap
            - name: jitsi-web-static
              configMap:
                name: web-custom-static-{{ .Release.Name }}-configmap
            - name: jitsi-web-html
              configMap:
                name: web-custom-html-{{ .Release.Name }}-configmap
            - name: jitsi-web-config
              configMap:
                name: web-{{ .Release.Name }}-configmap
