apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: web
  name: web
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: web
  template:
    metadata:
      labels:
        k8s-app: web
    spec:
      containers:
        - name: web
          ports:
          - containerPort: 80
          - containerPort: 443
          image: {{ .Values.webImageName }}:{{ .Values.webVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_SERVER
              value: prosody
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://prosody:5280
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_RECORDER_DOMAIN
              value: recorder.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: UTC
            - name: ENABLE_CLOSE_PAGE
              value: "1"
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_GUESTS
              value: "0"
            - name: ENABLE_PREJOIN_PAGE
              value: "0"
            - name: ENABLE_XMPP_WEBSOCKET
              value: "1"
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: ENABLE_END_CONFERENCE
              value: "0"
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  key: VIDEOCALL_SERVER_URL
                  name: jitsi-prosody-{{ .Release.Name }}-env
          volumeMounts:
            - mountPath: /config
              name: jitsi-web-config
            - mountPath: /usr/share/jitsi-meet/images/custom
              name: jitsi-web-images
            - mountPath: /usr/share/jitsi-meet
              name: jitsi-web-html
            - mountPath: /usr/share/jitsi-meet/static
              name: jitsi-web-static
            - mountPath: /usr/share/jitsi-meet/static/js
              name: jitsi-web-static-js
            - mountPath: /usr/share/jitsi-meet/css
              name: jitsi-web-css
      volumes:
            - name: jitsi-web-css
              configMap:
                name: jitsi-web-css-{{ .Release.Name }}-configmap
                items:
                  - key: styles.css
                    path: "styles.css"
                  - key: styles.css.map
                    path: "styles.css.map"
            - name: jitsi-web-images
              configMap:
                name: jitsi-web-images-{{ .Release.Name }}-configmap
            - name: jitsi-web-static
              configMap:
                name: web-custom-static-{{ .Release.Name }}-configmap
                items:
                  - key: authError.html
                    path: "authError.html"
                  - key: close2.html
                    path: "close2.html"
                  - key: close3.html
                    path: "close3.html"
                  - key: no_e2ee.html
                    path: "no_e2ee.html"
            - name: jitsi-web-static-js
              configMap:
                name: web-custom-static-{{ .Release.Name }}-configmap
                items:
                  - key: script.js
                    path: "script.js"
            - name: jitsi-web-html
              configMap:
                name: web-custom-html-{{ .Release.Name }}-configmap
                items:
                  - key: body.html
                    path: "body.html"
                  - key: dynamicBranding.json
                    path: "dynamicBranding.json"
            - name: jitsi-web-config
              configMap:
                name: web-{{ .Release.Name }}-configmap
                items:
                  - key: custom-config.js
                    path: "custom-config.js"
                  - key: custom-interface_config.js
                    path: "custom-interface_config.js"
