apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data:
  MONGO_URL: {{ print "mongodb://" .Values.global.rocketchatMongoUsername ":" .Values.global.rocketchatMongoPassword "@mongodb." .Release.Namespace ":27017/rocketchat?directConnection=true" | b64enc | quote }}
  MONGO_OPLOG_URL: {{ print "mongodb://" .Values.global.oplogMongoUsername ":" .Values.global.oplogMongoPassword "@mongodb." .Release.Namespace ":27017/oplog?authSource=local&replicaSet=rs0&directConnection=true" | b64enc | quote }}
