apiVersion: v1
data:
  ROOT_URL: "http://{{ .Values.global.domainName }}:3000"
  EXIT_UNHANDLEDPROMISEREJECTION: {{ .Values.exitUnhandledpromiserejection | default "0" | quote }}
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: rocketchat-{{ .Release.Name }}-env
  name: rocketchat-{{ .Release.Name }}-env
