apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    {{- if .Values.enableCors }}
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.enableCors }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.corsAllowHeaders }}"
    {{- end }}
  name: rocketchat
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - backend:
              service:
                name: rocketchat
                port:
                  number: 3000
            path: /(api|websocket)(.*)
            pathType: Prefix
  {{- if .Values.global.multitenancyEnabled }}
    {{- if not .Values.global.multitenancyWithSingleDomainEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
      http:
        paths:
          - backend:
              service:
                name: rocketchat
                port:
                  number: 3000
            path: /(api|websocket)(.*)
            pathType: Prefix
    {{- end }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.enableCors }}
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.enableCors }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.corsAllowHeaders }}"
  {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Type: binary";
      more_set_headers "Cache-Control: no-cache, no-store, must-revalidate";
      more_set_headers "Content-Disposition: attachment; filename=$1"
  name: rocketchat-file-upload
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - backend:
              service:
                name: rocketchat
                port:
                  number: 3000
            path: /file-upload(.*)
            pathType: Prefix
  {{- if .Values.global.multitenancyEnabled }}
    {{- if not .Values.global.multitenancyWithSingleDomainEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
      http:
        paths:
          - backend:
              service:
                name: rocketchat
                port:
                  number: 3000
            path: /file-upload(.*)
            pathType: Prefix
    {{- end }}
  {{- end }}
