apiVersion: v1
data:
{{- if .Values.global.enableTls }}
  APP_BASE_URL: "https://{{ .Values.global.domainName }}"
{{- else }}
  APP_BASE_URL: "http://{{ .Values.global.domainName }}"
{{- end }}

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: documentationservice-{{ .Release.Name }}-env
  name: documentationservice-{{ .Release.Name }}-env
