apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: documentationservice
  name: documentationservice
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: documentationservice
status:
  loadBalancer: {}
